### ISSUE TITLE
Support for xforms:copy element

### ISSUE THREAD

**Issue by hurufu** [AlainCouthures/declarative4all#2]
Dear @AlainCouthures,
Thank you for your effort implementing XForms.

I have a question does this implementation support `xforms:copy` element inside `xforms:select`? Or the only solutions is to dispatch additional events and insert nodes explicitly? Example is described in the [itemset specification](https://www.w3.org/TR/xforms/#ui-selection-commonelems-itemset)

Currently when I try to do something similar what is described under the link I get: `&lt;description&gt;Vanilla&lt;/description&gt;` instead of `<description>Vanilla</description>`

**Comment by AlainCouthures** [comment]
In the latest build of XSLTForms, the `xforms:copy` support is currently broken. This bug will be fixed as soon as possible.

**Comment by hurufu** [comment]
Thank you very much for a quick reply. Right now I've worked around this issue. I hope it will be fixed soon

**Comment by AlainCouthures** [comment]
The latest commit should fix this. Thank you for your feedback!

**Comment by hurufu** [comment]
I've tested with my latest code and `xforms:copy` works exactly as expected. I've also checked some abuses of this construct seems Ok. I'm closing the issue.

Thanks, and have a nice day.
